config/routes.rb
Rails.application.routes.draw do

get    '/about'           => 'apps#about'
get    '/news'           => 'apps#news'
get    '/contact'           => 'apps#contact'


  root to: "apps#index"
  resources :apps do
    resources :accounts
  end
  devise_for :users
end

app/models/account.rb
class Account < ActiveRecord::Base
	belongs_to :app
	validates :app, presence: true
  	validates :username, presence: true
  	belongs_to :user
end

app/models/app.rb
class App < ActiveRecord::Base
	has_many :accounts, dependent: :destroy
 	validates :name, presence: :true
  	belongs_to :user
end

# uniqueness: :true

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :apps
  has_many :accounts
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def new
    @app = App.find(params[:app_id])
    @account = current_user.accounts.new
  end
  def show
    @accounts = current_user.accounts.all
    @account = Account.find(params[:id])
    @app = App.find(params[:app_id])
    if current_user.id == @app.user_id
    else
      redirect_to root_path
    end
  end
  def create
    @app = App.find(params[:app_id])
    @account = @app.accounts.create(account_params.merge(user: current_user))
    redirect_to app_path(@app)
  end
  def edit
    @app = App.find(params[:app_id])
    @account = Account.find(params[:id])
    if current_user.id == @app.user_id
    else
      redirect_to root_path
    end
  end
  def update
    @app = App.find(params[:app_id])
    @account = Account.find(params[:id])
    @account.update(account_params.merge(user:current_user))
    redirect_to app_account_path(@app)
  end
  def destroy
    @app = App.find(params[:app_id])
    @account = Account.find(params[:id])
    @account.destroy
    redirect_to app_path(@app)
  end
  private
  def account_params
    params.require(:account).permit(:username, :email, :password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, :except => [:index, :news, :contact, :about]
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  @@popular = { "google" => "http://icons.iconarchive.com/icons/graphics-vibe/classic-3d-social/32/google-icon.png", "amazon" => "http://icons.iconarchive.com/icons/limav/flat-gradient-social/32/Amazon-icon.png", "gmail" => "http://icons.iconarchive.com/icons/marcus-roberto/google-play/32/Gmail-icon.png", "twitter" => "http://icons.iconarchive.com/icons/limav/flat-gradient-social/32/Twitter-icon.png", "facebook" => "http://icons.iconarchive.com/icons/danleech/simple/32/facebook-icon.png", "netflix" => "http://icons.iconarchive.com/icons/dakirby309/windows-8-metro/32/Web-Netflix-Metro-icon.png" }
  @@placeholder = "http://icons.iconarchive.com/icons/itzikgur/my-seven/32/Keys-icon.png"
  def about
  end
  def news
  end
  def contact
  end
  def index
    if current_user
      @placeholder = @@placeholder
      @popular = @@popular
      @apps = current_user.apps.all
      @accounts = current_user.accounts.all
    else
      @apps = nil
    end
  end
  def show
  @app = App.find(params[:id])
  @popular = @@popular
    if current_user.id == @app.user_id
    else
      redirect_to root_path
    end 
  end
  def edit
    @app = App.find(params[:id])
    if current_user.id == @app.user_id
    else
      redirect_to root_path
    end    
  end
  def new
    redirect_to root_path unless current_user
    @app = App.new
  end
  def create
    # @app = App.create!(app_params.merge(user: current_user))
    @app = current_user.apps.create!(app_params)
    redirect_to app_path(@app)
  end
  def update
    @app = current_user.apps.find(params[:id])
    @app.update(app_params.merge(user:current_user))
    redirect_to app_path(@app)
  end
  def destroy
    @app = current_user.apps.find(params[:id])
    @app.destroy
    redirect_to apps_path
  end
  private
  def app_params
    params.require(:app).permit(:name, :app_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/edit.html.erb
<h1 class="w3-text-teal">Edit Account</h1>

<%= form_for [@app, @account] do |f| %>
  <%= f.label :username %>*
  <br />
  <%= f.text_field :username %>
  <br />
  <br />
  <%= f.label :email %>
  <br />
  <%= f.text_field :email %>
  <br />
  <br />
  <%= f.label :password %>*
  <br />
  <%= f.password_field :password %>
  <br />
  <br />
  <%= f.submit %>
<% end %>
<p>*required</p>
<br />

<%= link_to "Delete!", app_account_path(@app), method: :delete, class: "delete" %>

app/views/accounts/new.html.erb
<h1 class="w3-text-teal">New <%= link_to @app.name, @app %> Account Credentials</h1>

<%= form_for [@app, @account] do |f| %>
  <%= f.label :username %>*
  <br />
  <%= f.text_field :username %>
  <br />
  <br />
  <%= f.label :email %>
  <br />
  <%= f.text_field :email %>
  <br />
  <br />
  <%= f.label :password %>*
  <br />
  <%= f.password_field :password %>
  <br />
  <br />
  <%= f.submit %>
<% end %>

<p>*required</p>

app/views/accounts/show.html.erb
<% warnings = 0 %>
<% site = 'https://haveibeenpwned.com/api/v2/breachedaccount/' %>
<% username = "#{@account.username}" %>
<% breaches = HTTParty.get(site+username) %>
<h1 class="w3-text-teal">Account Details</h1>
<a href=<%= edit_app_account_path(@app, @account) %>><button class="button">Edit Account</button></a>
<p><b><span class="w3-text-teal">Username:</span> <%= @account.username %></b></p>
<% if @account.email.length > 0 %> 
<p><b><span class="w3-text-teal">Email:</span> <%= @account.email %></b></p>
<% end %>
<!-- No breaches return an array length of 14, I don't know why -->
<% if breaches.length == 1 %>
	<% warnings += 1 %>
	<p style="color:red;""><b>Careful, an account "<%= @account.username %>" has been comprimised on a site!</b></p>
	<button class="button" onclick="showHidePass()">Show Password</button>
	<button class="breachbutton" onclick="showHideBreach()">Show Breaches</button>
	<br />
<% elsif breaches.length != 14 %>
	<% warnings += 1 %>
	<p style="color:red;""><b>Careful, an account "<%= @account.username %>" has been comprimised on <%= breaches.length %> sites!</b></p>
	<button class="button" onclick="showHidePass()">Show Password</button>
	<button class="breachbutton" onclick="showHideBreach()">Show Breaches</button>
<% else %>
	<button class="button" onclick="showHidePass()">Show Password</button>
<% end %>
<!-- haveibeenpwned API --> 
<div id="breaches" style="display: none;">
<p class="w3-text-teal">Data provided by <a href="https://haveibeenpwned.com/">haveibeenpwned.com:</a></p>
<div style="display:flex; align-content:flex-start; flex-wrap: wrap;">
<% if breaches.length != 14 %>
	<% breaches.each do |breach| %>
		<div class="breach" style="width:45%; height:45%; margin: 5px">
			<ul style="list-style: none; padding-left:0;">
			<li><span style="color:red">Site: </span><a href="http://<%= breach["Domain"] %>"><%= breach["Title"] %></a></li>
			<li><span style="color:red">Date Breached: </span> <%= breach["BreachDate"] %></li>
			<li><span style="color:red">Description: </span> <%= breach["Description"].html_safe %></li>
			</ul>
		</div>
	<% end %>
<% end %>
</div>
</div>
<br />
<!-- Password/Strength Info-->
<div id="password" style="display: none">
	<p><b><span class="w3-text-teal">Password:</span> <%= @account.password %></b></p>
	<!-- Warnings -->
	<p style="color: red"><b>Safety Warnings:</b></p>
	<ul style="list-style: none; padding-left:0">
	<!-- Warning: password contains "password" -->
	<% if @account.password.downcase.include? "password" %>
		<% warnings += 1 %>
		<li style="color:red">Consider not including "password" in your password</li>
	<% end %>
	<!-- Warning: password contains username -->
	<% if @account.password.downcase.include? @account.username.downcase %>
		<% warnings += 1 %>
		<li style="color:red">Consider not including your username in your password</li>
	<% end %>
	<!-- Warning: password contains app name -->
	<% if @account.password.downcase.include? @account.app.name.downcase %>
		<% warnings += 1 %>
		<li style="color:red">Dont include "<%= @account.app.name %>" in your password</li>
	<% end %>
	<!-- Warning: password is too short -->
	<% if @account.password.length <= 5 %>
		<% warnings += 1 %>
		<li style="color:red"><%= "Consider making your #{@account.app.name} password longer" %></li>
	<% end %>
	<!-- Warning: password does not contain a number -->
	<% if @account.password =~ /\d/ %>
	<% else %>
		<% warnings += 1 %>
		<li style="color:red"><%= "Consider including a number in your #{@account.app.name} password" %></li>
	<% end %>
	<!-- Warning: password does not contain a string -->
	<% if @account.password =~ /a/ %>
	<% else %>
		<% warnings += 1 %>
		<li style="color:red"><%= "Consider including a letter in your #{@account.app.name} password" %></li>
	<% end %>
	<!-- Warning: password does not contain different case letters -->
	<% if (@account.password =~ /[A-Z]/ && @account.password =~ /[a-z]/) %>
	<% else %>
		<% warnings += 1 %>
	<li style="color:red"><%= "Consider including different case letters in your #{@account.app.name} password" %></li><% end %>
	<!-- Warning: password does not contain a symbol -->
	<% symbols = ["!", "@", "#", "$", "%", "^", "&", "*", "(", ")"] %>
	<% if (@account.password.include? symbols[0]) || (@account.password.include? symbols[1]) || (@account.password.include? symbols[2]) || (@account.password.include? symbols[3]) || (@account.password.include? symbols[4]) || (@account.password.include? symbols[5]) || (@account.password.include? symbols[6]) || (@account.password.include? symbols[7]) || (@account.password.include? symbols[8]) || (@account.password.include? symbols[9]) %>
	<% else %>
		<% warnings += 1 %>
		<li style="color:red"><%= "Consider including a symbol (!, @, #, etc.) in your #{@account.app.name} password" %></li>
	<% end %> 
	<!-- Warning: password is used for other accounts -->
	<% similar = []%> 
	<% @accounts.each do |account| %>
		<% if account.password == @account.password && @account != account %>
			<% similar.push(account.app.name) %>
		<% end %> 
	<% end %>
	
	<% if similar.length > 0 %>
		<% warnings += 1 %>
		<li style="color:red">Consider choosing a unique password. This one matches a password you've used for accounts in these apps: <%= similar.uniq.join(", ") %></li>
	<% end %>
	</ul>
	<% if warnings == 0 %>
	<p style="color:green">None</p>
	<% end %>
</div>

<script>
function showHidePass() {
	var x = document.getElementById('password');
	if (x.style.display === 'none') {
		x.style.display = 'block';
	} else {
		x.style.display = 'none';
	}
	var y = document.getElementById('breaches');
	if (y.style.display === 'block') {
		y.style.display = 'none';
	} else {
		y.style.display = 'none';
	}
}
</script> 
<script>
function showHideBreach() {
	var x = document.getElementById('breaches');
	if (x.style.display === 'none') {
		x.style.display = 'block';
	} else {
		x.style.display = 'none';
	}
	var y = document.getElementById('password');
	if (y.style.display === 'block') {
		y.style.display = 'none';
	} else {
		y.style.display = 'none';
	}
}
</script> 

app/views/apps/about.html.erb
<h1 class="w3-text-teal">About SmartUser</h1>

<p>SmartUser is a password manager designed not only to store your passwords for safekeeping, but also to help you use best-practices when generating passwords.</p>

<p>Online security is a serious issue. According to one <a href="http://www.csid.com/wp-content/uploads/2012/09/CS_PasswordSurvey_FullReport_FINAL.pdf">consumer survey</a> on password habits:</p>
<ul>
	<li>61% of consumers reuse the same password on multiple websites</li>
	<li>54% of consumers have only five passwords or less
	</li>
	<li>44% of consumers change their password only once a year or less
	</li>
	<li>21% of consumers have had an online account comprimised
	</li>
</ul>

<p>That's why SmartUser contains a number of helpful tools to make sure you're using safe and secure passwords. For more information about SmartUser, please <a href=<%= contact_path %>>contact</a> the developer.</p>

app/views/apps/contact.html.erb
<h1 class="w3-text-teal">Contact Us</h1>
<p>If you would like to learn more about our solutions and technologies, please contact the developer:</p>
<p>Adam Whitehurst<br />
awhitehurst4 (at) gmail.com</a></p>

app/views/apps/edit.html.erb
<h1 class="w3-text-teal">Edit <%= @app.name %></h1>

<%= form_for @app do |f| %>
  <%= f.label :name %>*
  <%= f.text_field :name %>

  <%= f.label :app_url %>
  <%= f.text_field :app_url %>

  <%= f.submit %>
<% end %>
<p>*required</p>
<%= link_to "Delete", @app, method: :delete %>
<br />
<%= link_to( @app, method: :delete) do %>
<% end %>

app/views/apps/index.html.erb
<h1 class="w3-text-teal">Websites <% if current_user %> 
<a href="/apps/new" class="plus">(+)</a>
<% end %>
</h1>
<% if current_user %>
	<% if @apps.length == 0 %>
		<p>To get started, <a href="/apps/new">add a website</a> for which you would like to store account credentials (i.e. Gmail).
	<% end %>
	<% if @apps.length > 0 %>
		<div style="width: 763px; height:526px; display:flex; align-content:flex-start; flex-wrap: wrap;">
	  	<% @apps.each do |app| %>
	      <div class="app" style="width: 20%; height: 20%; word-wrap: break-word;">
	      <p>
	      <% if @popular.key?(app.name.downcase) %>
	      <a href=http://<%= app.app_url %>><img src=<%= @popular[app.name.downcase] %>></a>
	      <% else %>
	      <a href=http://<%= app.app_url %>><img src=<%= @placeholder %>></a>
	      <% end %>  
	      <a href="/apps/<%= app.id %>" style="font-size:18px"><%= app.name %></a>
	      </p>
	      </div>
	  	<% end %>
		</div>
	<% end %>
<% else %>
	<p><a href=<%= new_user_session_path %> class="w3-hover-black">Sign in</a> or <a href=<%= new_user_registration_path %> class="w3-hover-black">Register</a> to become a SmartUser!</p>
<% end %>

app/views/apps/new.html.erb
<h1 class="w3-text-teal">Website</h1>

<%= form_for @app do |f| %>
  <%= f.label :name %>*
  <%= f.text_field :name %>

  <%= f.label :app_url %>
  <%= f.text_field :app_url %>

  <%= f.submit "Create" %>
<% end %>

<p>*required</p>

app/views/apps/news.html.erb
<h1 class="w3-text-teal">SmartUser News</h1>
<h2 class="w3-text-teal" style="display:inline;">March 1, 2017</h2>
<p>SmartUser is live on Heroku!</p>
<h2 class="w3-text-teal" style="display:inline;">February 20, 2017</h2>
<p>SmartUser in under development.</p>

app/views/apps/show.html.erb
<h1 class="w3-text-teal" style="display:inline;">
<% if @popular.key?(@app.name.downcase) %>
	<a href=http://<%= @app.app_url %>><img src=<%= @popular[@app.name.downcase] %>></a>
<% end %>
<%= @app.name %>
</h1>
<a href=<%= edit_app_path(@app) %>><button class="button">Edit App</button></a>

<h3><span class="w3-text-teal">Accounts</span> <a href=<%= new_app_account_path(@app) %> class="plus">(+)</a></h3>

<% if @app.accounts.length == 0 %>
<p>Now <a href=<%= new_app_account_path(@app) %>>store account credentials</a> for <%= @app.name %>.</p>
<% end %>
<% if @app.accounts.length > 0 %>
<ul style="list-style: none; padding-left:0;">
  <% @app.accounts.each do |account| %>
    <li><%= link_to "#{account.username}", app_account_path(@app, account) %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<title>SmartUser</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="icon" type="image/png" href="http://icons.iconarchive.com/icons/itzikgur/my-seven/16/Keys-icon.png">
<style>
html,body,h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif}
.w3-sidenav a,.w3-sidenav h4 {padding: 12px;}
.w3-bar a {
    padding-top: 12px;
    padding-bottom: 12px;
}
/*footer {
  position: absolute;
  bottom: 0;
  width: 100%;
}*/
</style>
<body>

<!-- Navbar -->
<div class="w3-top">
  <div class="w3-bar w3-theme w3-top w3-left-align w3-large">
    <a class="w3-bar-item w3-button w3-opennav w3-right w3-hide-large w3-hover-white w3-large w3-theme-l1" href="javascript:void(0)" onclick="w3_open()"><i class="fa fa-bars"></i></a>
    <a href=<%= root_path %> class="w3-bar-item w3-button w3-hide-small w3-hover-white">SmartUser</a>
    <a href=<%= about_path %> class="w3-bar-item w3-button w3-hide-small w3-hover-white">About</a>
    <a href=<%= news_path %> class="w3-bar-item w3-button w3-hide-small w3-hover-white">News</a>
    <a href=<%= contact_path %> class="w3-bar-item w3-button w3-hide-small w3-hover-white">Contact</a>
  </div>
</div>

<!-- Sidenav -->
<nav class="w3-sidenav w3-collapse w3-theme-l5 w3-animate-left" style="z-index:3;width:250px;margin-top:51px;" id="mySidenav">
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="close menu">
    <i class="fa fa-remove"></i>
  </a>
  <h4><b>Menu</b></h4>
  <% if current_user %>
    <a href=<%= apps_path %> class="w3-hover-black">My Websites (<%= current_user.email %>)</a>
    <%= link_to "Log Out", destroy_user_session_path, method: :delete, :class=>"w3-hover-black" %>
  <% else %>
    <a href=<%= new_user_registration_path %> class="w3-hover-black">Register</a>
    <a href=<%= new_user_session_path %> class="w3-hover-black">Sign In</a>
  <% end %>  
</nav>

<!-- Overlay effect when opening sidenav on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- Main content: shift it to the right by 250 pixels when the sidenav is visible -->
<div class="w3-main" style="margin-left:250px">

  <div class="w3-row w3-padding-64">
    <div class="w3-twothird w3-container">
  <%= yield %>
    </div>
    <!-- <div class="w3-third w3-container">
      <p class="w3-border w3-padding-large w3-padding-32 w3-center">AD</p>
      <p class="w3-border w3-padding-large w3-padding-64 w3-center">AD</p>
    </div>
  </div> -->

  <div class="w3-row">
    <div class="w3-twothird w3-container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
<!--     <div class="w3-third w3-container">
      <p class="w3-border w3-padding-large w3-padding-32 w3-center">AD</p>
      <p class="w3-border w3-padding-large w3-padding-64 w3-center">AD</p>
    </div>-->  
</div>

  <!-- Pagination -->
<!--   <div class="w3-center w3-padding-jumbo">
    <div class="w3-bar">
      <a class="w3-button w3-black" href="#">1</a>
      <a class="w3-button w3-hover-black" href="#">2</a>
      <a class="w3-button w3-hover-black" href="#">3</a>
      <a class="w3-button w3-hover-black" href="#">4</a>
      <a class="w3-button w3-hover-black" href="#">5</a>
      <a class="w3-button w3-hover-black" href="#">»</a>
    </div>
  </div> -->

  <footer>
    <div class="w3-container w3-theme-l2 w3-padding-32">
      <h4>Created by <a href=<%= contact_path %>>Adam Whitehurst</a></h4><p>&copy; 2017 SmartUser.</p>
    </div>

    <div class="w3-container w3-theme-l1">
      <p>Powered by <a href="https://generalassemb.ly/" target="_blank">General Assembly</a></p>
    </div>
  </footer>

<!-- END MAIN -->
</div>

<script>
// Get the Sidenav
var mySidenav = document.getElementById("mySidenav");

// Get the DIV with overlay effect
var overlayBg = document.getElementById("myOverlay");

// Toggle between showing and hiding the sidenav, and add overlay effect
function w3_open() {
    if (mySidenav.style.display === 'block') {
        mySidenav.style.display = 'none';
        overlayBg.style.display = "none";
    } else {
        mySidenav.style.display = 'block';
        overlayBg.style.display = "block";
    }
}

// Close the sidenav with the close button
function w3_close() {
    mySidenav.style.display = "none";
    overlayBg.style.display = "none";
}
</script>

</body>
</html>